### ISSUE TITLE
Error at Stormdash level

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/Stormspotter#11]
To start with, I ran Stormspotter --cli and it completed with "value" string at the end just before the completion time. I am logged using the account which has permissions into the subscriptions.

After it i ran stormdash command and got the below result. Please advise how to resolve it...

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/bin/stormdash", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/lib/python3.8/site-packages/Stormdash.py", line 171, in main
    parser = DashParser(args.dbuser, args.dbpass, args.db)
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/lib/python3.8/site-packages/stormspotter/dash/core/context.py", line 30, in __init__
    self.processExistingFiles()
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/lib/python3.8/site-packages/stormspotter/dash/core/context.py", line 40, in processExistingFiles
    event = self.event_handler.on_created(FileCreatedEvent(str(file)))
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/lib/python3.8/site-packages/stormspotter/dash/core/context.py", line 35, in on_created
    self.parseInputFile(src)
  File "/root/.local/share/virtualenvs/Stormspotter-Kjgaye4t/lib/python3.8/site-packages/stormspotter/dash/core/context.py", line 395, in parseInputFile
    if resource["type"].lower() in validAzure.keys():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by mdaslamansari** [comment]
Still waiting for the response. Is there any way to get the quick response? Please advise.

**Comment by legra-ms** [comment]
@mdaslamansari Sorry for the delayed response. Been a busy month. It's likely that a null object showed up in the JSON. This randomly happened to me before. The immediate solution would be to check for the existence of `resource["type"]`. 

I'm currently focusing on getting out a full release in [v1.0.0](../tree/dev-v1.0.0) which should solve a lot of the issues that have been reported so efforts on the existing code is pretty non-existent.

**Comment by mdaslamansari** [comment]
Thanks @legra-ms. What is the time frame for v1.0.0 release...Waiting for it...Also, if it is still away, can you please provide the quick fix of the problem in code? Many thanks...

**Comment by legra-ms** [comment]
@mdaslamansari  New beta release is out. Closing this as this issue should no longer applicable with the new beta release. Feel free to open up new issues!
