### ISSUE TITLE
Error uploading results

### ISSUE THREAD

**Issue by blockanz** [Azure/Stormspotter#56]
Just downloaded and ran latest Stormcollector and when uploading results I am getting errors and no data is uploaded.

An example of the errors is as follows:

stormspotter-backend_1   |                                                                       ^}
stormspotter-backend_1   | 2021-11-17 20:23:07.954 | ERROR    | backend.db:query:172 - [=] Failed to insert new document. Trying again.
stormspotter-backend_1   | 2021-11-17 20:23:07.954 | ERROR    | backend.parser:_process_json:693 - An error has been caught in function '_process_json', process 'MainProcess' (1), thread 'MainThread' (140142363948864):
stormspotter-backend_1   | (type=<class 'AttributeError'>, value=AttributeError("'Neo4j' object has no attribute 'session'"), traceback=<traceback object at 0x7f756ba54cc0>)
stormspotter-backend_1   | 2021-11-17 20:23:07.965 | ERROR    | backend.db:query:171 - {code: Neo.ClientError.Statement.SyntaxError} {message: Type mismatch: expected Node or Relationship but was Boolean, Float, Integer, Number, Point, String, Duration, Date, Time, LocalTime, LocalDateTime, DateTime, List<Boolean>, List<Float>, List<Integer>, List<Number>, List<Point>, List<String>, List<Duration>, List<Date>, List<Time>, List<LocalTime>, List<LocalDateTime> or List<DateTime> (line 1, column 70 (offset: 69))
stormspotter-backend_1   | "MERGE (obj:AADObject{id:'ff135bcc-8d47-4d4d-94a2-e1fb4748c381'}) SET obj.odata.type = 'Microsoft.DirectoryServices.ServicePrincipal', obj.objectType = 'ServicePrincipal', obj.objectId = 'ff135bcc-8d47-4d4d-94a2-e1fb4748c381', obj.deletionTimestamp = 'None', obj.accountEnabled = True, obj.appBranding = 'None', obj.appCategory = 'None', obj.appData = 'None', obj.appDisplayName = 'SharePoint Online Web Client Extensibility', obj.appId = '08e18876-6177-487e-b8b5-cf950c1e598c', obj.applicationTemplateId = 'None', obj.appMetadata = 'None', obj.appOwnerTenantId = 'f8cdef31-a31e-4b4a-93e4-5f571e91255a', obj.appRoleAssignmentRequired = 'False', obj.appRoles = 'None', obj.authenticationPolicy = 'None', obj.createdDateTime = '2020-06-03T09:59:52Z', obj.errorUrl = 'None', obj.homepage = 'None', obj.informationalUrls = 'None', obj.keyCredentials = 'None', obj.loginUrl = 'None', obj.logoutUrl = 'None', obj.managedIdentityResourceId = 'None', obj.microsoftFirstParty = True, obj.notificationEmailAddresses = 'None', obj.oauth2Permissions = 'None', obj.passwordCredentials = 'None', obj.preferredSingleSignOnMode = 'None', obj.preferredTokenSigningKeyEndDateTime = 'None', obj.preferredTokenSigningKeyThumbprint = 'None', obj.publisherName = 'Microsoft Services', obj.replyUrls = ['https://geneticnz-my.sharepoint.com/_forms/spfxsinglesignon.aspx', 'https://geneticnz-admin.sharepoint.com/_forms/spfxsinglesignon.aspx', 'https://geneticnz.sharepoint.com/_forms/spfxsinglesignon.aspx', 'https://dev.fluidpreview.office.net/spfxsinglesignon', 'https://fluidpreview.office.net/spfxsinglesignon'], obj.samlMetadataUrl = 'None', obj.samlSingleSignOnSettings = 'None', obj.servicePrincipalNames = ['api://geneticnz.sharepoint.com', 'api://geneticnz-admin.sharepoint.com', 'api://geneticnz-my.sharepoint.com', '08e18876-6177-487e-b8b5-cf950c1e598c'], obj.tags = 'None', obj.tokenEncryptionKeyId = 'None', obj.verifiedPublisher = 'None', obj.useCustomTokenSigningKey = 'None', obj.owners = 'None', obj.type = 'AADServicePrincipal', obj.name = 'SharePoint Online Web Client Extensibility', obj.passwordCredentialCount = '0', obj.keyCredentialCount = '0', obj.raw = '{"odata.type":"Microsoft.DirectoryServices.ServicePrincipal","objectType":"ServicePrincipal","objectId":"ff135bcc-8d47-4d4d-94a2-e1fb4748c381","deletionTimestamp":null,"accountEnabled":true,"appBranding":null,"appCategory":null,"appData":null,"appDisplayName":"SharePoint Online Web Client Extensibility","appId":"08e18876-6177-487e-b8b5-cf950c1e598c","applicationTemplateId":null,"appMetadata":null,"appOwnerTenantId":"f8cdef31-a31e-4b4a-93e4-5f571e91255a","appRoleAssignmentRequired":false,"appRoles":[],"authenticationPolicy":null,"createdDateTime":"2020-06-03T09:59:52Z","displayName":"SharePoint Online Web Client Extensibility","errorUrl":null,"homepage":null,"informationalUrls":{"termsOfService":null,"support":null,"privacy":null,"marketing":null},"keyCredentials":[],"loginUrl":null,"logoutUrl":null,"managedIdentityResourceId":null,"microsoftFirstParty":true,"notificationEmailAddresses":[],"oauth2Permissions":[],"passwordCredentials":[],"preferredSingleSignOnMode":null,"preferredTokenSigningKeyEndDateTime":null,"preferredTokenSigningKeyThumbprint":null,"publisherName":"Microsoft Services","replyUrls":["https://geneticnz-my.sharepoint.com/_forms/spfxsinglesignon.aspx","https://geneticnz-admin.sharepoint.com/_forms/spfxsinglesignon.aspx","https://geneticnz.sharepoint.com/_forms/spfxsinglesignon.aspx","https://dev.fluidpreview.office.net/spfxsinglesignon","https://fluidpreview.office.net/spfxsinglesignon"],"samlMetadataUrl":null,"samlSingleSignOnSettings":null,"servicePrincipalNames":["api://geneticnz.sharepoint.com","api://geneticnz-admin.sharepoint.com","api://geneticnz-my.sharepoint.com","08e18876-6177-487e-b8b5-cf950c1e598c"],"tags":[],"tokenEncryptionKeyId":null,"verifiedPublisher":{"displayName":null,"verifiedPublisherId":null,"addedDateTime":null},"useCustomTokenSigningKey":null,"owners":[]}', obj :AADServicePrincipal"
stormspotter-backend_1   |                                                                       ^}
stormspotter-backend_1   | 2021-11-17 20:23:07.966 | ERROR    | backend.db:query:172 - [=] Failed to insert new document. Trying again.
stormspotter-backend_1   | 2021-11-17 20:23:07.966 | ERROR    | backend.parser:_process_json:693 - An error has been caught in function '_process_json', process 'MainProcess' (1), thread 'MainThread' (140142363948864):
stormspotter-backend_1   | (type=<class 'AttributeError'>, value=AttributeError("'Neo4j' object has no attribute 'session'"), traceback=<traceback object at 0x7f7568153280>)
stormspotter-backend_1   | 2021-11-17 20:23:07.972 | INFO     | backend.parser:process_sqlite:723 - Finished processing AADServicePrincipal.sqlite
stormspotter-backend_1   | 2021-11-17 20:23:08.107 | INFO     | backend.parser:process:757 - Completed ingestion of results_20211118-080850.zip

This happens for everything. Any ideas?

Thanks

**Comment by blockanz** [comment]
Here are the entries from the start of the upload. This is using Docker version also:

stormspotter-backend_1   | 2021-11-17 20:25:39.332 | INFO     | uvicorn.protocols.http.httptools_impl:send:452 - 172.18.0.1:60228 - "POST /api/upload HTTP/1.1" 200
stormspotter-backend_1   | 2021-11-17 20:25:39.334 | INFO     | backend.db:__init__:32 - Connecting to bolt://stormspotter-neo4j:7687
stormspotter-backend_1   | 2021-11-17 20:25:39.689 | INFO     | backend.db:shutdown:187 - Closing the neo4j session
stormspotter-backend_1   | 2021-11-17 20:25:39.966 | INFO     | backend.parser:process_sqlite:717 - Processing AADRole
stormspotter-backend_1   | 2021-11-17 20:25:39.974 | INFO     | backend.parser:process_sqlite:717 - Processing AADApplication
stormspotter-backend_1   | 2021-11-17 20:25:39.976 | INFO     | backend.parser:process_sqlite:717 - Processing AADUser
stormspotter-backend_1   | 2021-11-17 20:25:39.977 | INFO     | backend.parser:process_sqlite:717 - Processing AADServicePrincipal
stormspotter-backend_1   | 2021-11-17 20:25:39.980 | INFO     | backend.parser:process_sqlite:717 - Processing AADGroup
stormspotter-backend_1   | 2021-11-17 20:25:40.033 | ERROR    | backend.db:query:171 - {code: Neo.ClientError.Statement.SyntaxError} {message: Type mismatch: expected Node or Relationship but was Boolean, Float, Integer, Number, Point, String, Duration, Date, Time, LocalTime, LocalDateTime, DateTime, List<Boolean>, List<Float>, List<Integer>, List<Number>, List<Point>, List<String>, List<Duration>, List<Date>, List<Time>, List<LocalTime>, List<LocalDateTime> or List<DateTime> (line 1, column 70 (offset: 69))

**Comment by v1sion** [comment]
Having the same issue.
Steps to reproduce:
- `docker-compose up`
- `python3 sscollector.pyz --cli `
- Upload results.zip in "Stormspotter Upload"

**Comment by legra-ms** [comment]
Hi all,

I'm currently working on a completely new release of Stormspotter. The issues here are **probably** related to trying to ingesting the "raw" field (I'm not entirely sure) but the new collector and parser that will be released should address this and some other issues that have come up.

I don't have a timeline for the release of the new version.

**Comment by jllangley** [comment]
I am having the same issue as well. Thanks @legra-ms for the comment, look forward to an update.

**Comment by jllangley** [comment]
Any update on this issue?  I just tried again and the AADUser.sqlite never populates in the graph database.  I get the same error as above Type Mismatch.

**Comment by Tanq16** [comment]
Reposting for this issue - just faced this same issue on a local build. The error seems to be indicating that there is a syntax error with the "CREATE INDEX" statement but that seems correct to me.

ErrLog for reference → 
```
2022-11-14 10:40:33.171 | INFO     | uvicorn.protocols.http.httptools_impl:send:452 - 127.0.0.1:52321 - "POST /api/upload HTTP/1.1" 200
2022-11-14 10:40:33.171 | INFO     | backend.db:__init__:32 - Connecting to bolt://localhost:7687
2022-11-14 10:40:33.200 | ERROR    | backend.db:query:172 - {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid create index syntax, use `CREATE INDEX FOR ...` instead. (line 1, column 1 (offset: 0))
"CREATE INDEX ON : AADApplication(id)"
 ^}
2022-11-14 10:40:33.201 | ERROR    | backend.db:query:173 - [=] Failed to insert new document. Trying again.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/fastapi/applications.py", line 179, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/routing.py", line 44, in app
    await response(scope, receive, send)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/responses.py", line 142, in __call__
    await self.background()
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/background.py", line 35, in __call__
    await task()
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/starlette/background.py", line 18, in __call__
    await self.func(*self.args, **self.kwargs)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/backend/parser.py", line 737, in process
    self.neo = Neo4j(server=server, user=neo_user, password=neo_pass)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/backend/db.py", line 36, in __init__
    self.create_indexes()
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/backend/db.py", line 108, in create_indexes
    self.query(statement)
  File "/Users/tanishqrupaal/.shiv/ssbackend_9d8fb862227922663386f75ea7fde6036173641246c76469ae6e705c8c484044/site-packages/backend/db.py", line 175, in query
    self.session.run(statement)
AttributeError: 'Neo4j' object has no attribute 'session'
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [73563]
```
