### ISSUE TITLE
Frontend container is not starting

### ISSUE THREAD

**Issue by pennywise-01** [Azure/Stormspotter#85]
![image](https://github.com/Azure/Stormspotter/assets/54774679/dc282a1a-fd67-4914-8853-6ea21ab425a5)
As you can see in the above image, the response said that the frontend container should be up an running but when i list out the running container its not there. Please help me solve this

**Comment by hulto** [comment]
I'm having the same issue.
Seems like a frontend dependency has fallen out of date.
```
$ docker-compose up
[+] Running 3/0
 ✔ Container stormspotter-stormspotter-neo4j-1     Created                                                                                                                                                                                                                0.0s 
 ✔ Container stormspotter-stormspotter-frontend-1  Created                                                                                                                                                                                                                0.0s 
 ✔ Container stormspotter-stormspotter-backend-1   Created                                                                                                                                                                                                                0.0s 
Attaching to stormspotter-stormspotter-backend-1, stormspotter-stormspotter-frontend-1, stormspotter-stormspotter-neo4j-1
stormspotter-stormspotter-frontend-1  | file:///usr/local/lib/node_modules/@quasar/cli/bin/quasar.js:25
stormspotter-stormspotter-frontend-1  |   const { default: appPaths } = await import('../lib/app-paths.js')
stormspotter-stormspotter-frontend-1  |                                 ^^^^^
stormspotter-stormspotter-frontend-1  | 
stormspotter-stormspotter-frontend-1  | SyntaxError: Unexpected reserved word
stormspotter-stormspotter-frontend-1  |     at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
stormspotter-stormspotter-frontend-1  |     at async link (internal/modules/esm/module_job.js:42:21)
stormspotter-stormspotter-frontend-1  | 
stormspotter-stormspotter-frontend-1 exited with code 1

```
